version: '3'
services:
  node1:
    build: ./node
    environment:
      - NODE_ID=node1
    ports:
      - "5001:5000"

  node2:
    build: ./node
    environment:
      - NODE_ID=node2
    ports:
      - "5002:5000"

  node3:
    build: ./node
    environment:
      - NODE_ID=node3
    ports:
      - "5003:5000"

  router:
    build: ./router
    ports:
      - "8080:5000"
    depends_on:
      - node1
      - node2
      - node3
